apiVersion: v1
kind: Service
metadata:
  name: {{ include "micros3.fullname" . }}
  labels:
    {{- include "micros3.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "micros3.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.service.headless.s3.port }}
      targetPort: {{ .Values.service.headless.s3.port }}
    - name: internal
      port: {{ .Values.service.headless.internal.port }}
      targetPort: {{ .Values.service.headless.internal.port }}
