apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "micros3.fullname" . }}
  labels:
    {{- include "micros3.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "micros3.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "micros3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "micros3.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "micros3.serviceAccountName" . }}
      containers:
        - name: {{ include "micros3.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MICROS3_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: {{ .Values.service.headless.s3.port }}
              name: s3
            - containerPort: {{ .Values.service.headless.internal.port }}
              name: internal
          volumeMounts:
            - name: config-volume
              mountPath: /etc/micros3
            - name: data-volume
              mountPath: /data
          args: ["-config", "/etc/micros3/config.yaml"]
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.httpGet.path }}
              port: s3
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.httpGet.path }}
              port: s3
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "micros3.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
          limits:
            storage: {{ .Values.persistence.size }}
  {{- end }}
