apiVersion: v1
kind: Service
metadata:
  name: micros3-leader
spec:
  type: NodePort
  ports:
    - name: s3
      port: 30010
      targetPort: 30010
      nodePort: 30010
  selector:
    app: micros3
    role: leader
