apiVersion: v2
name: micros3
description: A lightweight, high-performance distributed S3-compatible object storage server
type: application
version: "0.2.1"
appVersion: "0.2.1"
home: https://github.com/paucpauc/micros3
