name: Release Helm Chart

on:
  push:
    branches: [main]
    paths:
     - helm/**
     - .github/workflows/release-chart.yml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Ensure gh-pages branch exists
        run: |
          if ! git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            printf 'apiVersion: v1\nentries: {}\n' > index.yaml
            git add index.yaml
            git commit -m "Initialize gh-pages"
            git push origin gh-pages
            git checkout main
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
